In [2]:
## 한국은행 API이용한 일별 데이터 불러오기

from urllib.request import urlopen
import json
import pandas as pd
import datetime
import timedelta

c:\users\jhpark1\anaconda3\envs\tc\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
c:\users\jhpark1\anaconda3\envs\tc\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
c:\users\jhpark1\anaconda3\envs\tc\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
  stacklevel=1)

In [3]:
# 통계항목 및 API코드 기준 엑셀파일은 별도 작성함
ecos_std =pd.read_excel('한국은행_API로드_기준리스트.xlsx', converters={'통계항목코드' : str})
ecos_std

    No     통계자료명     통계코드            통계항목명     통계항목코드  단위
0    1  주식시장(일별)  064Y001        KOSPI_거래량    0002000  만주
1    2  주식시장(일별)  064Y001       KOSPI_거래대금    0003000  억원
2    3  주식시장(일별)  064Y001     KOSPI_외국인순매수    0030000  억원
3    4  주식시장(일별)  064Y001     KOSPI_거래량시간외    0087000  만주
4    5  주식시장(일별)  064Y001    KOSPI_거래대금시간외    0088000  억원
5    6  주식시장(일별)  064Y001       KOSPI_시가총액    0183000  억원
6    7  주식시장(일별)  064Y001       KOSDAQ_거래량    0090000  만주
7    8  주식시장(일별)  064Y001      KOSDAQ_거래대금    0091000  억원
8    9  주식시장(일별)  064Y001    KOSDAQ_외국인순매수    0113000  억원
9   10  시장금리(일별)  060Y001    콜금리(1일, 전체거래)  010101000  연%
10  11  시장금리(일별)  060Y001  콜금리(1일, 중개회사거래)  010102000  연%
11  12  시장금리(일별)  060Y001     KORIBOR(3개월)  010150000  연%
12  13  시장금리(일별)  060Y001     KORIBOR(6개월)  010151000  연%
13  14  시장금리(일별)  060Y001    KORIBOR(12개월)  010152000  연%
14  15  시장금리(일별)  060Y001          CD(91일)  010502000  연%
15  16  시장금리(일별)  060Y001          CP(91일)  010503000  연%
16  17  시장금리(일별)  060Y001     국민주택채권1종(5년)  010503500  연%
17  18  시장금리(일별)  060Y001          국고채(1년)  010190000  연%
18  19  시장금리(일별)  060Y001          국고채(3년)  010200000  연%
19  20  시장금리(일별)  060Y001          국고채(5년)  010200001  연%
20  21  시장금리(일별)  060Y001         국고채(10년)  010210000  연%
21  22  시장금리(일별)  060Y001         국고채(20년)  010220000  연%
22  23  시장금리(일별)  060Y001         국고채(30년)  010230000  연%
23  24  시장금리(일별)  060Y001        통안증권(91일)  010400001  연%
24  25  시장금리(일별)  060Y001         통안증권(1년)  010400000  연%
25  26  시장금리(일별)  060Y001         통안증권(2년)  010400002  연%
26  27  시장금리(일별)  060Y001          산금채(1년)  010260000  연%
27  28  시장금리(일별)  060Y001      회사채(3년,AA-)  010300000  연%
28  29  시장금리(일별)  060Y001    회사채(3년)(BBB-)  010320000  연%
29  30  시장금리(일별)  060Y001  회사채(AA-, 민평)수익률  010310000  연%
30  31  시장금리(일별)  060Y001          MMF(7일)  010501000  연%
31  32  시장금리(일별)  060Y001         CMA(수시형)  010504000  연%
32  33  시장금리(일별)  060Y001          MMF(7일)  010504000  연%
33  34  시장금리(일별)  060Y001         CMA(수시형)  010504000  연%

In [4]:
# 현재 날짜 가져오기 , format = YYYYMMDD
today_iso = datetime.datetime.now().isoformat()[:10].replace('-','')

# 현재 날짜 가져오기 , format = YYYY-MM-DD
today = datetime.datetime.now()
today_s = str(today.year) + '-' +  str(today.month) + '-' +str(today.day)

# 19970101 ~ 현재 갯수 구하기
tot_len = len(pd.date_range("2003-1-2", today_s))

In [5]:
# 한국은행 ECOS API 데이터 로드
## 통계표 : 주식시장(일별)
from urllib.request import urlopen
from tqdm import tqdm_notebook
import json

key = '💛'

for i in tqdm_notebook(ecos_std.index):
    # url="http://ecos.bok.or.kr/api/StatisticSearch/"+key+"/json/kr/1/24/010Y002/MM/201401/201912/?/?/?/"
    url="http://ecos.bok.or.kr/api/StatisticSearch/" + key + "/json/kr/1/" + str(tot_len) + "/"  + str(ecos_std["통계코드"][i]) + "/DD/20000101/" + today_iso + "/" + str(ecos_std["통계항목코드"][i]) +"/?/?/"

    result = urlopen(url)
    html = result.read()
    data = json.loads(html)
    data = data["StatisticSearch"]["row"]
    data = pd.DataFrame(data)
    data["TIME"] = data["TIME"].astype(str)

    #컬럼 정리 : 
    # TIME => Date : YYYY-MM-DD
    # DATA_VALU => kr_bs_rate
    data["Date"] = data["TIME"].str[:4] + "-" + data["TIME"].str[4:6] + "-" + data["TIME"].str[6:]
    data = data.rename(columns={'DATA_VALUE' : ecos_std["통계항목명"][i]})
    data = data[["Date",ecos_std["통계항목명"][i]]]
    data = data.reset_index(drop=True)
    data = data.sort_values(["Date"])
    data.to_csv("D:\\시세모니터링\\융합분석\\DATA\\" + datetime.datetime.now().isoformat()[:10].replace("-","") + "\\"+ ecos_std["통계항목명"][i] + ".csv", index=False)

c:\users\jhpark1\anaconda3\envs\tc\lib\site-packages\ipykernel_launcher.py:9: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  if __name__ == '__main__':

HBox(children=(FloatProgress(value=0.0, max=34.0), HTML(value='')))

            Date KOSPI_거래량
0     2003-01-02     74286
1     2003-01-03    100575
2     2003-01-06     72180
3     2003-01-07     69012
4     2003-01-08     60487
...          ...       ...
4307  2020-06-05     84007
4308  2020-06-08     84291
4309  2020-06-09     80525
4310  2020-06-10     69521
4311  2020-06-11     81382

[4312 rows x 2 columns]
            Date KOSPI_거래대금
0     2003-01-02      13532
1     2003-01-03      22705
2     2003-01-06      15986
3     2003-01-07      18700
4     2003-01-08      14885
...          ...        ...
4307  2020-06-05     125834
4308  2020-06-08     129256
4309  2020-06-09     145235
4310  2020-06-10     126818
4311  2020-06-11     166430

[4312 rows x 2 columns]
            Date KOSPI_외국인순매수
0     2003-01-02          -60
1     2003-01-03         2539
2     2003-01-06         1535
3     2003-01-07         1331
4     2003-01-08          125
...          ...          ...
4311  2020-06-05         -720
4312  2020-06-08          114
4313  2020-06-09         -231
4314  2020-06-10         -477
4315  2020-06-11        -1209

[4316 rows x 2 columns]
            Date KOSPI_거래량시간외
0     2000-01-04        19590
1     2000-01-05        25770
2     2000-01-06        20352
3     2000-01-07        21566
4     2000-01-08        21566
...          ...          ...
5085  2020-06-03       115200
5086  2020-06-05        85459
5087  2020-06-08        85404
5088  2020-06-09        81709
5089  2020-06-10        70629

[5090 rows x 2 columns]
            Date KOSPI_거래대금시간외
0     2000-01-04         37710
1     2000-01-05         47981
2     2000-01-06         37269
3     2000-01-07         36967
4     2000-01-08         36967
...          ...           ...
5085  2020-06-03        169988
5086  2020-06-05        127789
5087  2020-06-08        131455
5088  2020-06-09        146899
5089  2020-06-10        128882

[5090 rows x 2 columns]
            Date KOSPI_시가총액
0     2003-01-02    2618570
1     2003-01-03    2726580
2     2003-01-06    2748210
3     2003-01-07    2689030
4     2003-01-08    2687120
...          ...        ...
4311  2020-06-05   14667690
4312  2020-06-08   14687150
4313  2020-06-09   14720510
4314  2020-06-10   14767120
4315  2020-06-11   14643920

[4316 rows x 2 columns]
            Date KOSDAQ_거래량
0     2003-01-02      24662
1     2003-01-03      34182
2     2003-01-06      32270
3     2003-01-07      37841
4     2003-01-08      35718
...          ...        ...
4311  2020-06-05     112502
4312  2020-06-08     132559
4313  2020-06-09     153257
4314  2020-06-10     157727
4315  2020-06-11     143000

[4316 rows x 2 columns]
            Date KOSDAQ_거래대금
0     2003-01-02        6849
1     2003-01-03        9609
2     2003-01-06       10024
3     2003-01-07       11829
4     2003-01-08       11130
...          ...         ...
4311  2020-06-05       86562
4312  2020-06-08       91205
4313  2020-06-09      103431
4314  2020-06-10      122133
4315  2020-06-11      133168

[4316 rows x 2 columns]
            Date KOSDAQ_외국인순매수
0     2003-01-02            -9
1     2003-01-03           204
2     2003-01-06            55
3     2003-01-07           129
4     2003-01-08            25
...          ...           ...
4311  2020-06-05          1003
4312  2020-06-08           140
4313  2020-06-09           936
4314  2020-06-10           622
4315  2020-06-11          -502

[4316 rows x 2 columns]
            Date 콜금리(1일, 전체거래)
0     2000-01-04          4.69
1     2000-01-05          4.71
2     2000-01-06          4.78
3     2000-01-07          4.77
4     2000-01-08          4.78
...          ...           ...
5114  2020-06-05          0.47
5115  2020-06-08          0.46
5116  2020-06-09           0.5
5117  2020-06-10          0.49
5118  2020-06-11          0.49

[5119 rows x 2 columns]
            Date 콜금리(1일, 중개회사거래)
0     2000-01-04            4.65
1     2000-01-05            4.65
2     2000-01-06            4.65
3     2000-01-07            4.65
4     2000-01-08            4.65
...          ...             ...
5114  2020-06-05            0.47
5115  2020-06-08            0.46
5116  2020-06-09             0.5
5117  2020-06-10            0.49
5118  2020-06-11            0.49

[5119 rows x 2 columns]
            Date KORIBOR(3개월)
0     2005-08-01         3.51
1     2005-08-02         3.51
2     2005-08-03         3.51
3     2005-08-04         3.51
4     2005-08-05         3.51
...          ...          ...
3686  2020-06-05         0.66
3687  2020-06-08         0.65
3688  2020-06-09         0.65
3689  2020-06-10         0.65
3690  2020-06-11         0.65

[3691 rows x 2 columns]
            Date KORIBOR(6개월)
0     2006-02-01         4.47
1     2006-02-02         4.47
2     2006-02-03         4.48
3     2006-02-06         4.49
4     2006-02-07         4.49
...          ...          ...
3558  2020-06-05         0.69
3559  2020-06-08         0.69
3560  2020-06-09         0.68
3561  2020-06-10         0.68
3562  2020-06-11         0.68

[3563 rows x 2 columns]
            Date KORIBOR(12개월)
0     2004-07-26          4.12
1     2004-07-27          4.11
2     2004-07-28          4.11
3     2004-07-29           4.1
4     2004-07-30          4.09
...          ...           ...
3941  2020-06-05          0.85
3942  2020-06-08          0.85
3943  2020-06-09          0.86
3944  2020-06-10          0.86
3945  2020-06-11          0.86

[3946 rows x 2 columns]
            Date CD(91일)
0     2000-01-04    7.35
1     2000-01-05    7.37
2     2000-01-06    7.38
3     2000-01-07    7.38
4     2000-01-08    7.38
...          ...     ...
5114  2020-06-05    0.79
5115  2020-06-08    0.79
5116  2020-06-09    0.79
5117  2020-06-10    0.79
5118  2020-06-11    0.79

[5119 rows x 2 columns]
            Date CP(91일)
0     2000-01-04    7.99
1     2000-01-05       8
2     2000-01-06    7.99
3     2000-01-07    7.98
4     2000-01-08    7.98
...          ...     ...
5114  2020-06-05     1.6
5115  2020-06-08    1.58
5116  2020-06-09    1.57
5117  2020-06-10    1.56
5118  2020-06-11    1.56

[5119 rows x 2 columns]
            Date 국민주택채권1종(5년)
0     2003-09-30         4.55
1     2003-10-01         4.41
2     2003-10-02          4.4
3     2003-10-06         4.47
4     2003-10-07         4.48
...          ...          ...
4143  2020-06-05        1.345
4144  2020-06-08        1.331
4145  2020-06-09        1.284
4146  2020-06-10        1.277
4147  2020-06-11        1.267

[4148 rows x 2 columns]
            Date 국고채(1년)
0     2000-02-01    8.71
1     2000-02-02    8.71
2     2000-02-03    8.67
3     2000-02-07    8.63
4     2000-02-08    8.65
...          ...     ...
5043  2020-06-05    0.73
5044  2020-06-08   0.732
5045  2020-06-09   0.722
5046  2020-06-10    0.72
5047  2020-06-11   0.718

[5048 rows x 2 columns]
            Date 국고채(3년)
0     2000-01-04    9.04
1     2000-01-05    9.11
2     2000-01-06    9.16
3     2000-01-07    9.17
4     2000-01-10    9.23
...          ...     ...
5063  2020-06-05   0.894
5064  2020-06-08   0.902
5065  2020-06-09   0.861
5066  2020-06-10    0.84
5067  2020-06-11   0.837

[5068 rows x 2 columns]
            Date 국고채(5년)
0     2000-01-04   10.06
1     2000-01-05   10.12
2     2000-01-06   10.16
3     2000-01-07   10.16
4     2000-01-10    10.2
...          ...     ...
5063  2020-06-05   1.189
5064  2020-06-08   1.191
5065  2020-06-09   1.134
5066  2020-06-10   1.122
5067  2020-06-11   1.113

[5068 rows x 2 columns]
            Date 국고채(10년)
0     2000-12-18     7.15
1     2000-12-19      7.2
2     2000-12-20      7.2
3     2000-12-21     7.24
4     2000-12-22     7.24
...          ...      ...
4828  2020-06-05    1.452
4829  2020-06-08    1.453
4830  2020-06-09    1.397
4831  2020-06-10    1.398
4832  2020-06-11    1.383

[4833 rows x 2 columns]
            Date 국고채(20년)
0     2006-01-25     5.79
1     2006-01-26     5.75
2     2006-01-27     5.75
3     2006-01-31     5.74
4     2006-02-01     5.67
...          ...      ...
3562  2020-06-05    1.562
3563  2020-06-08    1.566
3564  2020-06-09    1.523
3565  2020-06-10    1.528
3566  2020-06-11    1.515

[3567 rows x 2 columns]
            Date 국고채(30년)
0     2012-09-11     3.02
1     2012-09-12     3.02
2     2012-09-13     3.04
3     2012-09-14     3.04
4     2012-09-17     3.06
...          ...      ...
1907  2020-06-05    1.585
1908  2020-06-08    1.583
1909  2020-06-09    1.542
1910  2020-06-10    1.546
1911  2020-06-11    1.542

[1912 rows x 2 columns]

            Date 통안증권(91일)
0     2006-09-25      4.54
1     2006-09-26      4.55
2     2006-09-27      4.55
3     2006-09-28      4.55
4     2006-09-29      4.54
...          ...       ...
3397  2020-06-05     0.608
3398  2020-06-08      0.61
3399  2020-06-09     0.606
3400  2020-06-10     0.607
3401  2020-06-11     0.605

[3402 rows x 2 columns]
            Date 통안증권(1년)
0     2000-01-04     8.99
1     2000-01-05     9.04
2     2000-01-06     9.05
3     2000-01-07     9.04
4     2000-01-08     9.05
...          ...      ...
5114  2020-06-05    0.674
5115  2020-06-08    0.674
5116  2020-06-09    0.666
5117  2020-06-10    0.661
5118  2020-06-11    0.659

[5119 rows x 2 columns]
            Date 통안증권(2년)
0     2000-01-04     9.43
1     2000-01-05     9.51
2     2000-01-06     9.57
3     2000-01-07     9.57
4     2000-01-08     9.58
...          ...      ...
5198  2020-06-05    0.799
5199  2020-06-08    0.796
5200  2020-06-09    0.784
5201  2020-06-10    0.775
5202  2020-06-11    0.774

[5203 rows x 2 columns]
            Date 산금채(1년)
0     2003-09-30    4.09
1     2003-10-01    4.04
2     2003-10-02    4.03
3     2003-10-06    4.05
4     2003-10-07    4.05
...          ...     ...
4143  2020-06-05     0.8
4144  2020-06-08   0.803
4145  2020-06-09   0.796
4146  2020-06-10   0.796
4147  2020-06-11   0.794

[4148 rows x 2 columns]
            Date 회사채(3년,AA-)
0     2000-01-04        9.95
1     2000-01-05       10.05
2     2000-01-06       10.13
3     2000-01-07       10.14
4     2000-01-08       10.16
...          ...         ...
5114  2020-06-05       2.224
5115  2020-06-08       2.227
5116  2020-06-09       2.204
5117  2020-06-10       2.205
5118  2020-06-11       2.204

[5119 rows x 2 columns]
            Date 회사채(3년)(BBB-)
0     2000-09-30         11.24
1     2000-10-02         11.33
2     2000-10-04         11.32
3     2000-10-05         11.32
4     2000-10-06         11.31
...          ...           ...
4980  2020-06-05         8.513
4981  2020-06-08         8.518
4982  2020-06-09           8.5
4983  2020-06-10           8.5
4984  2020-06-11           8.5

[4985 rows x 2 columns]
            Date 회사채(AA-, 민평)수익률
0     2002-08-19            5.85
1     2002-08-20            5.89
2     2002-08-21            5.95
3     2002-08-22            5.97
4     2002-08-23            6.01
...          ...             ...
4422  2020-06-05           1.672
4423  2020-06-08           1.668
4424  2020-06-09           1.623
4425  2020-06-10           1.611
4426  2020-06-11           1.608

[4427 rows x 2 columns]
            Date MMF(7일)
0     2000-01-04    5.82
1     2000-01-05    5.83
2     2000-01-06    5.83
3     2000-01-07    5.83
4     2000-01-08    5.83
...          ...     ...
5114  2020-06-05    1.01
5115  2020-06-08    1.01
5116  2020-06-09    1.01
5117  2020-06-10    1.01
5118  2020-06-11    1.01

[5119 rows x 2 columns]
            Date CMA(수시형)
0     2000-01-04     7.29
1     2000-01-05     7.29
2     2000-01-06     7.29
3     2000-01-07     7.29
4     2000-01-08     7.29
...          ...      ...
5196  2020-06-05     0.24
5197  2020-06-08     0.24
5198  2020-06-09     0.24
5199  2020-06-10     0.24
5200  2020-06-11     0.24

[5201 rows x 2 columns]
            Date MMF(7일)
0     2000-01-04    7.29
1     2000-01-05    7.29
2     2000-01-06    7.29
3     2000-01-07    7.29
4     2000-01-08    7.29
...          ...     ...
5196  2020-06-05    0.24
5197  2020-06-08    0.24
5198  2020-06-09    0.24
5199  2020-06-10    0.24
5200  2020-06-11    0.24

[5201 rows x 2 columns]
            Date CMA(수시형)
0     2000-01-04     7.29
1     2000-01-05     7.29
2     2000-01-06     7.29
3     2000-01-07     7.29
4     2000-01-08     7.29
...          ...      ...
5196  2020-06-05     0.24
5197  2020-06-08     0.24
5198  2020-06-09     0.24
5199  2020-06-10     0.24
5200  2020-06-11     0.24

[5201 rows x 2 columns]