In [24]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler

import torch
import torch.nn as nn
import torch.nn.functional as F

import matplotlib.pyplot as plt

In [25]:
import os
os.getcwd()

os.listdir(os.curdir)

]

In [26]:
raw_dt = pd.read_csv('./train.csv')
raw_dt

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [27]:
# constant_num = 10
# raw_dt = raw_dt.replace(['Ex', 'Gd', 'TA', 'Av', 'Fa', 'Mn','Po', 'No', 'NA'], [constant_num*2,  constant_num*1.5, 
#                                                                            constant_num, constant_num,
#                                                                             constant_num * 0.5,
#                                                                            constant_num*0.3, constant_num*0.1, 
#                                                                            0, 0])


# raw_dt = raw_dt.replace(['GLQ', 'ALQ' , 'BLQ', 'Rec', 'LwQ', 'Unf'], [constant_num*2,  constant_num*1.3, 
#                                                         constant_num*0.9, constant_num*0.7,
#                                                        constant_num*0.3, constant_num*0.05])

# raw_dt['Street'] = raw_dt['Street'].replace(['Grvl', 'Pave'], [constant_num*0.7, constant_num*2])
# raw_dt['Alley'] = raw_dt['Alley'].replace(['Grvl', 'Pave'], [constant_num*0.7, constant_num*2 ])
# raw_dt['LotShape'] = raw_dt['LotShape'].replace(['Reg', 'IR1', 'IR2' , 'IR3'], [constant_num*5,constant_num*2, constant_num, constant_num*0.8 ])
# raw_dt['LandContour'] = raw_dt['LandContour'].replace(['Lvl', 'Bnk', 'HLS', 'Low'], [constant_num*5,constant_num*1.5, constant_num*0.8, constant_num*0.4])
# raw_dt['Utilities'] = raw_dt['Utilities'].replace(['AllPub', 'NoSewr', 'NoSeWa', 'ELO'], [constant_num*3, constant_num*2.3, constant_num*1.5, constant_num])
# raw_dt['LotConfig'] = raw_dt['LotConfig'].replace(['Inside', 'Corner', 'CulDSac', 'FR2', 'FR3'], [constant_num*1.5, constant_num*2, constant_num,
#                                                                                                  constant_num*3, constant_num*4])
# raw_dt['LandSlope'] = raw_dt['LandSlope'].replace(['Gtl', 'Mod', 'Sev'], [constant_num*1.5, constant_num*0.9, constant_num*0.3 ])
# raw_dt['RoofStyle'] = raw_dt['RoofStyle'].replace(['', ''], [constant_num,constant_num ])
# raw_dt['MSZoning'] = raw_dt['MSZoning'].replace(['A', 'C',  'C (all)', 'FV', 'I', 'RH','RL', 'RP', 'RM'], [constant_num*1.2, constant_num*1.5, constant_num*2, constant_num*1.1, constant_num*0.5,
#                                                                              constant_num*0.8, constant_num, constant_num*0.5, constant_num*0.9])
# raw_dt['BldgType'] = raw_dt['BldgType'].replace(['1Fam', '2fmCon', 'Duplex', 'Twnhs', 'TwnhsE' ,'TwnhsI'], [constant_num*3, constant_num*1.5, 
#                                                                                                   constant_num*1.1, constant_num*0.9,
#                                                                                                   constant_num*0.8, constant_num*0.7 ])
# # raw_dt[''] = raw_dt[''].replace(['', ''], [constant_num,constant_num ])



# raw_dt['CentralAir'] = raw_dt['CentralAir'].replace(['N', 'Y'], [0, 1])
# raw_dt['GarageType'] = raw_dt['GarageType'].replace(['2Types', 'Attchd', 'Basment', 'BuiltIn', 'CarPort', 'Detchd'], [constant_num*2, constant_num*1.6,
#                                                                                                                      constant_num*1.3, constant_num*1.2,
#                                                                                                                      constant_num*1.1, constant_num*0.9])

# raw_dt['GarageFinish'] = raw_dt['GarageFinish'].replace(['Fin', 'RFn', 'Unf'], [constant_num*1.6, constant_num*1.3, constant_num*0.8])
# raw_dt['PavedDrive'] = raw_dt['PavedDrive'].replace(['Y', 'P', 'N'], [constant_num*1.7, constant_num*1.3, constant_num*0.95])
# raw_dt['Fence'] = raw_dt['Fence'].replace(['GdPrv', 'MnPrv', 'GdWo', 'MnWw'], [constant_num*2, constant_num*1.5, constant_num*1.2, constant_num*0.8])
# raw_dt['MiscFeature'] = raw_dt['MiscFeature'].replace(['Elev', 'Gar2', 'Othr', 'Shed', 'TenC'], [constant_num*1.5, constant_num*1.8, constant_num*1.3
#                                                                                                  ,constant_num*1.4,constant_num*1.9])

In [28]:
raw_dt['price_per_lot'] = raw_dt['SalePrice'] / raw_dt['LotArea']
raw_dt['net_area'] = ((raw_dt['1stFlrSF'] + raw_dt['2ndFlrSF']) - raw_dt['LowQualFinSF']) 
+ raw_dt['GrLivArea'] + raw_dt['GarageArea'] + raw_dt['PoolArea'] 

# raw_dt['price_per_'] = raw_dt['SalePrice'] / raw_dt['net_area']
raw_dt

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,price_per_lot,net_area
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,0,2,2008,WD,Normal,208500,24.674556,1710
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,0,5,2007,WD,Normal,181500,18.906250,1262
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,0,9,2008,WD,Normal,223500,19.866667,1786
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,0,2,2006,WD,Abnorml,140000,14.659686,1717
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,0,12,2008,WD,Normal,250000,17.531557,2198
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,0,8,2007,WD,Normal,175000,22.104332,1647
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,MnPrv,NaN,0,2,2010,WD,Normal,210000,15.939279,2073
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,GdPrv,Shed,2500,5,2010,WD,Normal,266500,29.473568,2340
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,0,4,2010,WD,Normal,142125,14.626428,1078
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,0,6,2008,WD,Normal,147500,14.843514,1256

In [29]:
raw_dt[['LotArea', 'net_area']]

      LotArea  net_area
0        8450      1710
1        9600      1262
2       11250      1786
3        9550      1717
4       14260      2198
...       ...       ...
1455     7917      1647
1456    13175      2073
1457     9042      2340
1458     9717      1078
1459     9937      1256

[1460 rows x 2 columns]

In [30]:
raw_dt = raw_dt.fillna(0)

In [31]:
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']

raw_dt_num = raw_dt.select_dtypes(include=numerics)
raw_dt_num

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice,price_per_lot,net_area
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,0,0,0,0,2,2008,208500,24.674556,1710
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,0,0,0,0,0,5,2007,181500,18.906250,1262
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,0,0,0,0,9,2008,223500,19.866667,1786
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,272,0,0,0,0,2,2006,140000,14.659686,1717
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,0,0,0,0,0,12,2008,250000,17.531557,2198
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917,6,5,1999,2000,0.0,0,...,0,0,0,0,0,8,2007,175000,22.104332,1647
1456,1457,20,85.0,13175,6,6,1978,1988,119.0,790,...,0,0,0,0,0,2,2010,210000,15.939279,2073
1457,1458,70,66.0,9042,7,9,1941,2006,0.0,275,...,0,0,0,0,2500,5,2010,266500,29.473568,2340
1458,1459,20,68.0,9717,5,6,1950,1996,0.0,49,...,112,0,0,0,0,4,2010,142125,14.626428,1078
1459,1460,20,75.0,9937,5,6,1965,1965,0.0,830,...,0,0,0,0,0,6,2008,147500,14.843514,1256

In [32]:
numerics = ['object']

raw_dt_str = raw_dt.select_dtypes(include=numerics)
raw_dt_str

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,RL,Pave,0,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,0,0,0,WD,Normal
1,RL,Pave,0,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,...,Attchd,RFn,TA,TA,Y,0,0,0,WD,Normal
2,RL,Pave,0,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,0,0,0,WD,Normal
3,RL,Pave,0,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,...,Detchd,Unf,TA,TA,Y,0,0,0,WD,Abnorml
4,RL,Pave,0,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,...,Attchd,RFn,TA,TA,Y,0,0,0,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,RL,Pave,0,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,...,Attchd,RFn,TA,TA,Y,0,0,0,WD,Normal
1456,RL,Pave,0,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,...,Attchd,Unf,TA,TA,Y,0,MnPrv,0,WD,Normal
1457,RL,Pave,0,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,...,Attchd,RFn,TA,TA,Y,0,GdPrv,Shed,WD,Normal
1458,RL,Pave,0,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,...,Attchd,Unf,TA,TA,Y,0,0,0,WD,Normal
1459,RL,Pave,0,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,...,Attchd,Fin,TA,TA,Y,0,0,0,WD,Normal

In [33]:
raw_dt_num2 = pd.get_dummies(data = raw_dt_str, columns=raw_dt_str.columns)
raw_dt_num2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Columns: 268 entries, MSZoning_C (all) to SaleCondition_Partial
dtypes: uint8(268)
memory usage: 382.2 KB

In [34]:
raw_dt_num = pd.concat([raw_dt_num, raw_dt_num2], axis = 1)
raw_dt_num

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,0,0,1,0,0,0,0,1,0
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,0,0,0,1,0,0,0,0,1,0
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,0,0,1,0,0,0,0,1,0
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,0,0,1,1,0,0,0,0,0
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917,6,5,1999,2000,0.0,0,...,0,0,0,1,0,0,0,0,1,0
1456,1457,20,85.0,13175,6,6,1978,1988,119.0,790,...,0,0,0,1,0,0,0,0,1,0
1457,1458,70,66.0,9042,7,9,1941,2006,0.0,275,...,0,0,0,1,0,0,0,0,1,0
1458,1459,20,68.0,9717,5,6,1950,1996,0.0,49,...,0,0,0,1,0,0,0,0,1,0
1459,1460,20,75.0,9937,5,6,1965,1965,0.0,830,...,0,0,0,1,0,0,0,0,1,0

In [35]:
train_data = raw_dt_num.drop(columns=['Id', 'SalePrice', 'price_per_lot'])
train_data

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,60,65.0,8450,7,5,2003,2003,196.0,706,0,...,0,0,0,1,0,0,0,0,1,0
1,20,80.0,9600,6,8,1976,1976,0.0,978,0,...,0,0,0,1,0,0,0,0,1,0
2,60,68.0,11250,7,5,2001,2002,162.0,486,0,...,0,0,0,1,0,0,0,0,1,0
3,70,60.0,9550,7,5,1915,1970,0.0,216,0,...,0,0,0,1,1,0,0,0,0,0
4,60,84.0,14260,8,5,2000,2000,350.0,655,0,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,62.0,7917,6,5,1999,2000,0.0,0,0,...,0,0,0,1,0,0,0,0,1,0
1456,20,85.0,13175,6,6,1978,1988,119.0,790,163,...,0,0,0,1,0,0,0,0,1,0
1457,70,66.0,9042,7,9,1941,2006,0.0,275,0,...,0,0,0,1,0,0,0,0,1,0
1458,20,68.0,9717,5,6,1950,1996,0.0,49,1029,...,0,0,0,1,0,0,0,0,1,0
1459,20,75.0,9937,5,6,1965,1965,0.0,830,290,...,0,0,0,1,0,0,0,0,1,0

In [36]:
price_data = pd.DataFrame(raw_dt_num['price_per_lot'], columns = ['price_per_lot'])
price_data

      price_per_lot
0         24.674556
1         18.906250
2         19.866667
3         14.659686
4         17.531557
...             ...
1455      22.104332
1456      15.939279
1457      29.473568
1458      14.626428
1459      14.843514

[1460 rows x 1 columns]

In [37]:
min_max_scaler1  = MinMaxScaler()

min_max_scaler1.fit(train_data)

train_data_scaled = min_max_scaler1.fit_transform(train_data)
train_data_scaled = pd.DataFrame(train_data_scaled, columns = train_data.columns)
train_data_scaled

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,0.235294,0.207668,0.033420,0.666667,0.500,0.949275,0.883333,0.122500,0.125089,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.000000,0.255591,0.038795,0.555556,0.875,0.753623,0.433333,0.000000,0.173281,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.235294,0.217252,0.046507,0.666667,0.500,0.934783,0.866667,0.101250,0.086109,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.294118,0.191693,0.038561,0.666667,0.500,0.311594,0.333333,0.000000,0.038271,0.000000,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.235294,0.268371,0.060576,0.777778,0.500,0.927536,0.833333,0.218750,0.116052,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,0.235294,0.198083,0.030929,0.555556,0.500,0.920290,0.833333,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1456,0.000000,0.271565,0.055505,0.555556,0.625,0.768116,0.633333,0.074375,0.139972,0.110583,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1457,0.294118,0.210863,0.036187,0.666667,1.000,0.500000,0.933333,0.000000,0.048724,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1458,0.000000,0.217252,0.039342,0.444444,0.625,0.565217,0.766667,0.000000,0.008682,0.698100,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1459,0.000000,0.239617,0.040370,0.444444,0.625,0.673913,0.250000,0.000000,0.147059,0.196744,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [38]:
# drop_col = ['Electrical_0',
# 'Exterior1st_AsphShn',
# 'Condition2_RRAe',
# 'Condition2_RRAn',
# 'RoofStyle_Shed',
# 'Utilities',
# 'RoofMatl_ClyTile',
# 'RoofMatl_Membran',
# 'RoofMatl_Metal',
# 'RoofMatl_Roll',
# 'SaleType_ConLI',
# 'Exterior1st_CBlock',
# 'Exterior1st_BrkComm',
# 'Heating_OthW',
# 'Exterior1st_ImStucc',
# 'Exterior1st_Stone',
# 'Functional_Sev',
# 'Neighborhood_Blueste',
# 'Exterior2nd_CBlock',
# 'Condition2_Artery',
# 'Exterior2nd_Other',
# 'Electrical_Mix',
# 'Heating_Floor',
# 'Condition2_PosA'
# ]
# drop_col

In [39]:
# train_data_scaled = train_data_scaled.drop(columns=drop_col)
train_data_scaled

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,0.235294,0.207668,0.033420,0.666667,0.500,0.949275,0.883333,0.122500,0.125089,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.000000,0.255591,0.038795,0.555556,0.875,0.753623,0.433333,0.000000,0.173281,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.235294,0.217252,0.046507,0.666667,0.500,0.934783,0.866667,0.101250,0.086109,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.294118,0.191693,0.038561,0.666667,0.500,0.311594,0.333333,0.000000,0.038271,0.000000,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.235294,0.268371,0.060576,0.777778,0.500,0.927536,0.833333,0.218750,0.116052,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,0.235294,0.198083,0.030929,0.555556,0.500,0.920290,0.833333,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1456,0.000000,0.271565,0.055505,0.555556,0.625,0.768116,0.633333,0.074375,0.139972,0.110583,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1457,0.294118,0.210863,0.036187,0.666667,1.000,0.500000,0.933333,0.000000,0.048724,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1458,0.000000,0.217252,0.039342,0.444444,0.625,0.565217,0.766667,0.000000,0.008682,0.698100,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1459,0.000000,0.239617,0.040370,0.444444,0.625,0.673913,0.250000,0.000000,0.147059,0.196744,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [40]:
min_max_scaler2  = MinMaxScaler()
min_max_scaler2.fit(price_data)

price_data_scaled = min_max_scaler2.fit_transform(price_data)
price_data_scaled = pd.DataFrame(price_data_scaled, columns =['price_per_lot' + '_scaled'])
price_data_scaled

      price_per_lot_scaled
0                 0.247719
1                 0.186350
2                 0.196568
3                 0.141171
4                 0.171725
...                    ...
1455              0.220374
1456              0.154784
1457              0.298775
1458              0.140817
1459              0.143127

[1460 rows x 1 columns]

In [41]:
numeric_x_df = pd.DataFrame(train_data_scaled, columns = train_data_scaled.columns)
numeric_x = torch.tensor(numeric_x_df.values, dtype = torch.float)

numeric_y_df = pd.DataFrame(price_data_scaled, columns = price_data_scaled.columns)
numeric_y = torch.tensor(numeric_y_df.values, dtype = torch.float)
# raw_dt['SalePrice']

In [42]:
class Net(nn.Module):
    def __init__(self, D_in, H1, H2, H3, H4, H5, H6, H7, H8, H9, H10, H11, H12, H13, H14, H15, H16, D_out):
        super(Net, self).__init__()
        
        self.linear1 = nn.Linear(D_in, H1)
        self.dropout1 = nn.Dropout(0.5)
        self.linear2 = nn.Linear(H1, H2)
        self.dropout2 = nn.Dropout(0.5)
        self.linear3 = nn.Linear(H2, H3)
        self.dropout3 = nn.Dropout(0.5)
        self.linear4 = nn.Linear(H3, H4)
        self.dropout4 = nn.Dropout(0.5)
        self.linear5 = nn.Linear(H4, H5)
        self.dropout5 = nn.Dropout(0.5)
        self.linear6 = nn.Linear(H5, H6)
        self.dropout6 = nn.Dropout(0.5)
        self.linear7 = nn.Linear(H6, H7)
        self.dropout7 = nn.Dropout(0.5)
        self.linear8 = nn.Linear(H7, H8)
        self.dropout8 = nn.Dropout(0.5)
        self.linear9 = nn.Linear(H8, H9)
        self.dropout9 = nn.Dropout(0.5)
        self.linear10 = nn.Linear(H9, H10)
        self.dropout10 = nn.Dropout(0.5)
        self.linear11 = nn.Linear(H10, H11)
        self.dropout11 = nn.Dropout(0.5)
        self.linear12 = nn.Linear(H11, H12)
        self.dropout12 = nn.Dropout(0.5)
        self.linear13 = nn.Linear(H12, H13)
        self.dropout13 = nn.Dropout(0.5)
        self.linear14 = nn.Linear(H13, H14)
        self.dropout14 = nn.Dropout(0.5)
        self.linear15 = nn.Linear(H14, H15)
        self.dropout15 = nn.Dropout(0.5)
        self.linear16 = nn.Linear(H15, H16)
        self.dropout16 = nn.Dropout(0.5)
        self.linear17 = nn.Linear(H16, D_out)
        
    def forward(self, x):
        y_pred = self.linear1(x).clamp(min=0)
        y_pred = F.relu(y_pred)
        y_pred = self.dropout1(y_pred)
        y_pred = self.linear2(y_pred).clamp(min=0)
        y_pred = F.relu(y_pred)
        y_pred = self.dropout2(y_pred)
        y_pred = self.linear3(y_pred).clamp(min=0)                 
        y_pred = F.relu(y_pred)
        y_pred = self.dropout3(y_pred)
        y_pred = self.linear4(y_pred).clamp(min=0)
        y_pred = F.relu(y_pred)
        y_pred = self.dropout4(y_pred)                
        y_pred = self.linear5(y_pred).clamp(min=0)               
        y_pred = F.relu(y_pred)
        y_pred = self.dropout5(y_pred) 
        y_pred = self.linear6(y_pred).clamp(min=0)                
        y_pred = F.relu(y_pred)
        y_pred = self.dropout6(y_pred)
        y_pred = self.linear7(y_pred).clamp(min=0)
        y_pred = F.relu(y_pred)
        y_pred = self.dropout7(y_pred)
        y_pred = self.linear8(y_pred).clamp(min=0)
        y_pred = F.relu(y_pred)
        y_pred = self.dropout8(y_pred)
        y_pred = self.linear9(y_pred).clamp(min=0)
        y_pred = F.relu(y_pred)
        y_pred = self.dropout9(y_pred)
        y_pred = self.linear10(y_pred).clamp(min=0)
        y_pred = F.relu(y_pred)
        y_pred = self.dropout10(y_pred)
        y_pred = self.linear11(y_pred).clamp(min=0)
        y_pred = F.relu(y_pred)
        y_pred = self.dropout11(y_pred)
        y_pred = self.linear12(y_pred).clamp(min=0)
        y_pred = F.relu(y_pred)
        y_pred = self.dropout2(y_pred)
        y_pred = self.linear13(y_pred).clamp(min=0)
        y_pred = F.relu(y_pred)
        y_pred = self.dropout13(y_pred)
        y_pred = self.linear14(y_pred).clamp(min=0)
        y_pred = F.relu(y_pred)
        y_pred = self.dropout14(y_pred)
        y_pred = self.linear15(y_pred).clamp(min=0)
        y_pred = F.relu(y_pred)                
        y_pred = self.dropout15(y_pred)
        y_pred = self.linear16(y_pred).clamp(min=0)
        y_pred = F.relu(y_pred)
        y_pred = self.dropout16(y_pred)
        y_pred = self.linear17(y_pred)
        y_pred = F.relu(y_pred)
        return y_pred

In [43]:
numeric_x.shape

torch.Size([1460, 305])

In [44]:
numeric_y.shape

torch.Size([1460, 1])

In [45]:
H1 = 600
H2 = 900
H3 = 1100
H4 = 1300
H5 = 1500
H6 = 1700
H7 = 1400
H8 = 1600
H9 = 2000
H10 = 2200
H11 = 1900
H12 = 1700
H13 = 1500
H14 = 1300
H15 = 1000
H16 = 500

D_in = numeric_x.shape[1]
D_out = numeric_y.shape[1]

In [ ]:
model1 = Net(D_in, H1, H2, H3,H4, H5,H6, H7, H8, H9, H10, H11, H12, H13, H14, H15, H16, D_out)
criterion = nn.MSELoss(reduction = 'sum')
optimizer = torch.optim.Adam(model1.parameters(), lr = 0.001)

model1.train()
losses1 = []
for t in range(50000):
    y_pred = model1(numeric_x)
    
    loss = criterion(y_pred, numeric_y)
    if t % 1000 == 0:
        print(t, loss.item())
    losses1.append(loss.item())
    
#     if torch.isnan(loss):
#         break
        
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

0 89.1993408203125

In [ ]:
plt.figure(figsize=(12, 10))
plt.plot(range(len(losses1)), losses1)
plt.show()

In [ ]:
model1.eval()
train_result = model1(numeric_x)
train_result

In [ ]:
predict_result_price0 = pd.DataFrame(train_result.data.numpy(), columns = ['predict_price_per_size'])
predict_result_price0 = min_max_scaler2.inverse_transform(predict_result_price0)
predict_result_price0 = pd.DataFrame(predict_result_price0, columns = ['predict_price_per_size'])
predict_result_price0

In [ ]:
result_price0 = pd.concat([raw_dt, predict_result_price0], axis = 1)
result_price0

In [ ]:
train_data_scaled["predict_price"] = result_price0['predict_price_per_size'] * result_price0['net_area']
train_data_scaled["100-MAPE"] = 100 - ((abs(result_price0['price_per_lot']- result_price0["predict_price_per_size"]) / result_price0['price_per_lot']) * 100)
train_data_scaled["100-MAPE"].mean()

In [ ]:
train_data_scaled[train_data_scaled["100-MAPE"] > 0]["100-MAPE"].mean()

In [ ]:
# train_data_scaled[train_data_scaled["100-MAPE"] > 0]["100-MAPE"].mean()
# 97.6059195902155
# 96.2046989043564
# 95.10873512283307
# 87.20362026952365
# 98.85125470439321
# 79.32329139542865
#80.64054297089811

In [95]:
del [[test, result]]

NameError: name 'test' is not defined

In [96]:
test = pd.read_csv('./test.csv')

# test['price_per_lot'] = test['SalePrice'] / test['LotArea']
test['net_area'] = ((test['1stFlrSF'] + test['2ndFlrSF']) - test['LowQualFinSF']) + test['GrLivArea'] + test['GarageArea'] + test['PoolArea']

# test['price_per_net'] = test['SalePrice'] / test['net_area']

test

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,net_area
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,2522.0
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,2970.0
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,3740.0
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,3678.0
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,0,NaN,NaN,NaN,0,1,2010,WD,Normal,3066.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,2184.0
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,2470.0
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml,3024.0
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,1940.0
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,4650.0

In [97]:
constant_num = 10
test = test.replace(['Ex', 'Gd', 'TA', 'Av', 'Fa', 'Mn','Po', 'No', 'NA'], [constant_num*2,  constant_num*1.5, 
                                                                           constant_num, constant_num,
                                                                            constant_num * 0.5,
                                                                           constant_num*0.3, constant_num*0.1, 
                                                                           0, 0])


test = test.replace(['GLQ', 'ALQ' , 'BLQ', 'Rec', 'LwQ', 'Unf'], [constant_num*2,  constant_num*1.3, 
                                                        constant_num*0.9, constant_num*0.7,
                                                       constant_num*0.3, constant_num*0.05])

test['Street'] = test['Street'].replace(['Grvl', 'Pave'], [constant_num*0.7, constant_num*2])
test['Alley'] = test['Alley'].replace(['Grvl', 'Pave'], [constant_num*0.7, constant_num*2 ])
test['LotShape'] = test['LotShape'].replace(['Reg', 'IR1', 'IR2' , 'IR3'], [constant_num*5,constant_num*2, constant_num, constant_num*0.8 ])
test['LandContour'] = test['LandContour'].replace(['Lvl', 'Bnk', 'HLS', 'Low'], [constant_num*5,constant_num*1.5, constant_num*0.8, constant_num*0.4])
test['Utilities'] = test['Utilities'].replace(['AllPub', 'NoSewr', 'NoSeWa', 'ELO'], [constant_num*3, constant_num*2.3, constant_num*1.5, constant_num])
test['LotConfig'] = test['LotConfig'].replace(['Inside', 'Corner', 'CulDSac', 'FR2', 'FR3'], [constant_num*1.5, constant_num*2, constant_num,
                                                                                                 constant_num*3, constant_num*4])
test['LandSlope'] = test['LandSlope'].replace(['Gtl', 'Mod', 'Sev'], [constant_num*1.5, constant_num*0.9, constant_num*0.3 ])
test['RoofStyle'] = test['RoofStyle'].replace(['', ''], [constant_num,constant_num ])

test['MSZoning'] = test['MSZoning'].replace(['A', 'C',  'C (all)', 'FV', 'I', 'RH','RL', 'RP', 'RM'], [constant_num*1.2, constant_num*1.5, constant_num*2, constant_num*1.1, constant_num*0.5,
                                                                             constant_num*0.8, constant_num, constant_num*0.5, constant_num*0.9])
test['BldgType'] = test['BldgType'].replace(['1Fam', '2fmCon', 'Duplex', 'Twnhs', 'TwnhsE' ,'TwnhsI'], [constant_num*3, constant_num*1.5, 
                                                                                                  constant_num*1.1, constant_num*0.9,
                                                                                                  constant_num*0.8, constant_num*0.7 ])

# test[''] = test[''].replace(['', ''], [constant_num,constant_num ])



test['CentralAir'] = test['CentralAir'].replace(['N', 'Y'], [0, 1])
test['GarageType'] = test['GarageType'].replace(['2Types', 'Attchd', 'Basment', 'BuiltIn', 'CarPort', 'Detchd'], [constant_num*2, constant_num*1.6,
                                                                                                                     constant_num*1.3, constant_num*1.2,
                                                                                                                     constant_num*1.1, constant_num*0.9])

test['GarageFinish'] = test['GarageFinish'].replace(['Fin', 'RFn', 'Unf'], [constant_num*1.6, constant_num*1.3, constant_num*0.8])
test['PavedDrive'] = test['PavedDrive'].replace(['Y', 'P', 'N'], [constant_num*1.7, constant_num*1.3, constant_num*0.95])
test['Fence'] = test['Fence'].replace(['GdPrv', 'MnPrv', 'GdWo', 'MnWw'], [constant_num*2, constant_num*1.5, constant_num*1.2, constant_num*0.8])
test['MiscFeature'] = test['MiscFeature'].replace(['Elev', 'Gar2', 'Othr', 'Shed', 'TenC'], [constant_num*1.5, constant_num*1.8, constant_num*1.3
                                                                                                 ,constant_num*1.4,constant_num*1.9])

In [98]:
test = test.fillna(0)

In [99]:
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']

test_num = test.select_dtypes(include=numerics)
test_num

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,net_area
0,1461,20,8.0,80.0,11622,20.0,0.0,50.0,50.0,30.0,...,0,120,0,0.0,15.0,0.0,0,6,2010,2522.0
1,1462,20,10.0,81.0,14267,20.0,0.0,20.0,50.0,30.0,...,0,0,0,0.0,0.0,18.0,12500,6,2010,2970.0
2,1463,60,10.0,74.0,13830,20.0,0.0,20.0,50.0,30.0,...,0,0,0,0.0,15.0,0.0,0,3,2010,3740.0
3,1464,60,10.0,78.0,9978,20.0,0.0,20.0,50.0,30.0,...,0,0,0,0.0,0.0,0.0,0,6,2010,3678.0
4,1465,120,10.0,43.0,5005,20.0,0.0,20.0,8.0,30.0,...,0,144,0,0.0,0.0,0.0,0,1,2010,3066.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,9.0,21.0,1936,20.0,0.0,50.0,50.0,30.0,...,0,0,0,0.0,0.0,0.0,0,6,2006,2184.0
1455,2916,160,9.0,21.0,1894,20.0,0.0,50.0,50.0,30.0,...,0,0,0,0.0,0.0,0.0,0,4,2006,2470.0
1456,2917,20,10.0,160.0,20000,20.0,0.0,50.0,50.0,30.0,...,0,0,0,0.0,0.0,0.0,0,9,2006,3024.0
1457,2918,85,10.0,62.0,10441,20.0,0.0,50.0,50.0,30.0,...,0,0,0,0.0,15.0,14.0,700,7,2006,1940.0
1458,2919,60,10.0,74.0,9627,20.0,0.0,50.0,50.0,30.0,...,0,0,0,0.0,0.0,0.0,0,11,2006,4650.0

In [100]:
numerics = ['object']

test_str = test.select_dtypes(include=numerics)
test_str

,Neighborhood,Condition1,Condition2,HouseStyle,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,Foundation,Heating,Electrical,Functional,SaleType,SaleCondition
0,NAmes,Feedr,Norm,1Story,Gable,CompShg,VinylSd,VinylSd,None,CBlock,GasA,SBrkr,Typ,WD,Normal
1,NAmes,Norm,Norm,1Story,Hip,CompShg,Wd Sdng,Wd Sdng,BrkFace,CBlock,GasA,SBrkr,Typ,WD,Normal
2,Gilbert,Norm,Norm,2Story,Gable,CompShg,VinylSd,VinylSd,None,PConc,GasA,SBrkr,Typ,WD,Normal
3,Gilbert,Norm,Norm,2Story,Gable,CompShg,VinylSd,VinylSd,BrkFace,PConc,GasA,SBrkr,Typ,WD,Normal
4,StoneBr,Norm,Norm,1Story,Gable,CompShg,HdBoard,HdBoard,None,PConc,GasA,SBrkr,Typ,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,MeadowV,Norm,Norm,2Story,Gable,CompShg,CemntBd,CmentBd,None,CBlock,GasA,SBrkr,Typ,WD,Normal
1455,MeadowV,Norm,Norm,2Story,Gable,CompShg,CemntBd,CmentBd,None,CBlock,GasA,SBrkr,Typ,WD,Abnorml
1456,Mitchel,Norm,Norm,1Story,Gable,CompShg,VinylSd,VinylSd,None,CBlock,GasA,SBrkr,Typ,WD,Abnorml
1457,Mitchel,Norm,Norm,SFoyer,Gable,CompShg,HdBoard,Wd Shng,None,PConc,GasA,SBrkr,Typ,WD,Normal
1458,Mitchel,Norm,Norm,2Story,Gable,CompShg,HdBoard,HdBoard,BrkFace,PConc,GasA,SBrkr,Typ,WD,Normal

In [101]:
test_num2 = pd.get_dummies(data = test_str, columns=test_str.columns)
test_num = pd.concat([test_num, test_num2], axis = 1)

In [102]:
add_dummy_col = np.setdiff1d(np.array(raw_dt_num.columns), np.array(test_num.columns))
# add_dummy_col = np.delete(add_dummy_col, ['SalePrice','price_per_net'])
add_dummy_col

array(['Condition2_RRAe', 'Condition2_RRAn', 'Condition2_RRNn',
       'Electrical_0', 'Electrical_Mix', 'Exterior1st_ImStucc',
       'Exterior1st_Stone', 'Exterior2nd_Other', 'Heating_Floor',
       'Heating_OthW', 'HouseStyle_2.5Fin', 'RoofMatl_ClyTile',
       'RoofMatl_Membran', 'RoofMatl_Metal', 'RoofMatl_Roll', 'SalePrice',
       'price_per_lot'], dtype=object)

In [103]:
add_dummy_col[:-2]

array(['Condition2_RRAe', 'Condition2_RRAn', 'Condition2_RRNn',
       'Electrical_0', 'Electrical_Mix', 'Exterior1st_ImStucc',
       'Exterior1st_Stone', 'Exterior2nd_Other', 'Heating_Floor',
       'Heating_OthW', 'HouseStyle_2.5Fin', 'RoofMatl_ClyTile',
       'RoofMatl_Membran', 'RoofMatl_Metal', 'RoofMatl_Roll'],
      dtype=object)

In [104]:
type(add_dummy_col)

numpy.ndarray

In [105]:
for i in add_dummy_col[:-2]:
    test_num[i] = 0

In [108]:
train_data_scaled = train_data_scaled.drop(columns=['predict_price', '100-MAPE'])

In [109]:
# test_data = test_num.drop(columns=['Id'])
test_data = test_num[train_data_scaled.columns]
test_data

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,LotConfig,LandSlope,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,20,8.0,80.0,11622,20.0,0.0,50.0,50.0,15.0,15.0,...,0,0,0,1,0,0,0,0,1,0
1,20,10.0,81.0,14267,20.0,0.0,20.0,50.0,20.0,15.0,...,0,0,0,1,0,0,0,0,1,0
2,60,10.0,74.0,13830,20.0,0.0,20.0,50.0,15.0,15.0,...,0,0,0,1,0,0,0,0,1,0
3,60,10.0,78.0,9978,20.0,0.0,20.0,50.0,15.0,15.0,...,0,0,0,1,0,0,0,0,1,0
4,120,10.0,43.0,5005,20.0,0.0,20.0,8.0,15.0,15.0,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,160,9.0,21.0,1936,20.0,0.0,50.0,50.0,15.0,15.0,...,0,0,0,1,0,0,0,0,1,0
1455,160,9.0,21.0,1894,20.0,0.0,50.0,50.0,15.0,15.0,...,0,0,0,1,1,0,0,0,0,0
1456,20,10.0,160.0,20000,20.0,0.0,50.0,50.0,15.0,15.0,...,0,0,0,1,1,0,0,0,0,0
1457,85,10.0,62.0,10441,20.0,0.0,50.0,50.0,15.0,15.0,...,0,0,0,1,0,0,0,0,1,0
1458,60,10.0,74.0,9627,20.0,0.0,50.0,50.0,15.0,9.0,...,0,0,0,1,0,0,0,0,1,0

In [110]:
test_data_scaled = min_max_scaler1.fit_transform(test_data)
test_data_scaled = pd.DataFrame(test_data_scaled, columns = test_data.columns)
test_data_scaled

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,LotConfig,LandSlope,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,0.000000,0.40,0.400,0.184147,1.0,0.0,1.000000,1.000000,0.166667,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.000000,0.50,0.405,0.232124,1.0,0.0,0.285714,1.000000,0.333333,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.235294,0.50,0.370,0.224197,1.0,0.0,0.285714,1.000000,0.166667,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.235294,0.50,0.390,0.154326,1.0,0.0,0.285714,1.000000,0.166667,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.588235,0.50,0.215,0.064121,1.0,0.0,0.285714,0.086957,0.166667,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,0.823529,0.45,0.105,0.008453,1.0,0.0,1.000000,1.000000,0.166667,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1455,0.823529,0.45,0.105,0.007691,1.0,0.0,1.000000,1.000000,0.166667,1.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1456,0.000000,0.50,0.800,0.336115,1.0,0.0,1.000000,1.000000,0.166667,1.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1457,0.382353,0.50,0.310,0.162724,1.0,0.0,1.000000,1.000000,0.166667,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1458,0.235294,0.50,0.370,0.147959,1.0,0.0,1.000000,1.000000,0.166667,0.5,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [111]:
model1.eval()
test_y = model1(torch.tensor(test_data_scaled.values, dtype = torch.float))
test_y

tensor([[0.1214],
        [0.0928],
        [0.0967],
        ...,
        [0.0587],
        [0.1153],
        [0.0795]], grad_fn=<AddmmBackward0>)

In [112]:
predict_result_price1 = pd.DataFrame(test_y.data.numpy(), columns = ['predict_price_per_size'])
predict_result_price1 = min_max_scaler2.inverse_transform(predict_result_price1)
predict_result_price1 = pd.DataFrame(predict_result_price1, columns = ['predict_price_per_size'])
predict_result_price1

      predict_price_per_size
0                  12.800030
1                  10.116992
2                  10.475223
3                  11.140975
4                  15.353312
...                      ...
1454               41.924030
1455               33.769684
1456                6.907579
1457               12.226761
1458                8.860167

[1459 rows x 1 columns]

In [113]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Columns: 181 entries, MSSubClass to SaleCondition_Partial
dtypes: float64(38), int64(28), uint8(115)
memory usage: 916.3 KB

In [114]:
test_data = pd.concat([test_data, predict_result_price1], axis = 1)
test_data['SalePrice'] = test_data['predict_price_per_size'] * test_data['net_area']
test_data

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,LotConfig,LandSlope,...,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,predict_price_per_size,SalePrice
0,20,8.0,80.0,11622,20.0,0.0,50.0,50.0,15.0,15.0,...,0,1,0,0,0,0,1,0,12.800030,32281.675041
1,20,10.0,81.0,14267,20.0,0.0,20.0,50.0,20.0,15.0,...,0,1,0,0,0,0,1,0,10.116992,30047.466230
2,60,10.0,74.0,13830,20.0,0.0,20.0,50.0,15.0,15.0,...,0,1,0,0,0,0,1,0,10.475223,39177.332478
3,60,10.0,78.0,9978,20.0,0.0,20.0,50.0,15.0,15.0,...,0,1,0,0,0,0,1,0,11.140975,40976.506044
4,120,10.0,43.0,5005,20.0,0.0,20.0,8.0,15.0,15.0,...,0,1,0,0,0,0,1,0,15.353312,47073.253178
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,160,9.0,21.0,1936,20.0,0.0,50.0,50.0,15.0,15.0,...,0,1,0,0,0,0,1,0,41.924030,91562.082184
1455,160,9.0,21.0,1894,20.0,0.0,50.0,50.0,15.0,15.0,...,0,1,1,0,0,0,0,0,33.769684,83411.119080
1456,20,10.0,160.0,20000,20.0,0.0,50.0,50.0,15.0,15.0,...,0,1,1,0,0,0,0,0,6.907579,20888.520172
1457,85,10.0,62.0,10441,20.0,0.0,50.0,50.0,15.0,15.0,...,0,1,0,0,0,0,1,0,12.226761,23719.916077
1458,60,10.0,74.0,9627,20.0,0.0,50.0,50.0,15.0,9.0,...,0,1,0,0,0,0,1,0,8.860167,41199.774456

In [115]:
test_data = pd.concat([test_data, test['Id']], axis = 1)
test_data

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,LotConfig,LandSlope,...,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,predict_price_per_size,SalePrice,Id
0,20,8.0,80.0,11622,20.0,0.0,50.0,50.0,15.0,15.0,...,1,0,0,0,0,1,0,12.800030,32281.675041,1461
1,20,10.0,81.0,14267,20.0,0.0,20.0,50.0,20.0,15.0,...,1,0,0,0,0,1,0,10.116992,30047.466230,1462
2,60,10.0,74.0,13830,20.0,0.0,20.0,50.0,15.0,15.0,...,1,0,0,0,0,1,0,10.475223,39177.332478,1463
3,60,10.0,78.0,9978,20.0,0.0,20.0,50.0,15.0,15.0,...,1,0,0,0,0,1,0,11.140975,40976.506044,1464
4,120,10.0,43.0,5005,20.0,0.0,20.0,8.0,15.0,15.0,...,1,0,0,0,0,1,0,15.353312,47073.253178,1465
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,160,9.0,21.0,1936,20.0,0.0,50.0,50.0,15.0,15.0,...,1,0,0,0,0,1,0,41.924030,91562.082184,2915
1455,160,9.0,21.0,1894,20.0,0.0,50.0,50.0,15.0,15.0,...,1,1,0,0,0,0,0,33.769684,83411.119080,2916
1456,20,10.0,160.0,20000,20.0,0.0,50.0,50.0,15.0,15.0,...,1,1,0,0,0,0,0,6.907579,20888.520172,2917
1457,85,10.0,62.0,10441,20.0,0.0,50.0,50.0,15.0,15.0,...,1,0,0,0,0,1,0,12.226761,23719.916077,2918
1458,60,10.0,74.0,9627,20.0,0.0,50.0,50.0,15.0,9.0,...,1,0,0,0,0,1,0,8.860167,41199.774456,2919

In [116]:
# test_data['SalePrice'] = test_data['predicted_SalePrice'] * test_data['net_area']
test_data.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,LotConfig,LandSlope,...,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,predict_price_per_size,SalePrice,Id
0,20,8.0,80.0,11622,20.0,0.0,50.0,50.0,15.0,15.0,...,1,0,0,0,0,1,0,12.800030,32281.675041,1461
1,20,10.0,81.0,14267,20.0,0.0,20.0,50.0,20.0,15.0,...,1,0,0,0,0,1,0,10.116992,30047.466230,1462
2,60,10.0,74.0,13830,20.0,0.0,20.0,50.0,15.0,15.0,...,1,0,0,0,0,1,0,10.475223,39177.332478,1463
3,60,10.0,78.0,9978,20.0,0.0,20.0,50.0,15.0,15.0,...,1,0,0,0,0,1,0,11.140975,40976.506044,1464
4,120,10.0,43.0,5005,20.0,0.0,20.0,8.0,15.0,15.0,...,1,0,0,0,0,1,0,15.353312,47073.253178,1465

In [117]:
result = test_data[['Id', 'SalePrice']]
# result = result.rename(columns={'predicted_SalePrice' : 'SalePrice'})
result

        Id     SalePrice
0     1461  32281.675041
1     1462  30047.466230
2     1463  39177.332478
3     1464  40976.506044
4     1465  47073.253178
...    ...           ...
1454  2915  91562.082184
1455  2916  83411.119080
1456  2917  20888.520172
1457  2918  23719.916077
1458  2919  41199.774456

[1459 rows x 2 columns]

In [119]:
result.to_csv('./Submission_0316.csv', index = False, encoding = 'utf-8')

In [55]:
price_data_scaled.columns

Index(['price_per_lot_scaled'], dtype='object')